backend:
  name: github
  repo: kosei-2025/expresscg
  branch: main
  auth_type: pkce
  app_id: Ov23li4Z6jDmgWBmRtlc

collections:
  - name: timer
    label: Projects JSON
    files:
      - file: "data/projects.json"
        label: projects.json
        name: projects
        fields:
          - label: JSON コード
            name: body
            widget: code
            output_code_only: true
            default_language: json
